#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyChoThueBangDia")]
	public partial class QuanLyThueDiaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDia(Dia instance);
    partial void UpdateDia(Dia instance);
    partial void DeleteDia(Dia instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiDia(LoaiDia instance);
    partial void UpdateLoaiDia(LoaiDia instance);
    partial void DeleteLoaiDia(LoaiDia instance);
    partial void InsertLogin(Login instance);
    partial void UpdateLogin(Login instance);
    partial void DeleteLogin(Login instance);
    partial void InsertNhatKyGhiNo(NhatKyGhiNo instance);
    partial void UpdateNhatKyGhiNo(NhatKyGhiNo instance);
    partial void DeleteNhatKyGhiNo(NhatKyGhiNo instance);
    partial void InsertNhatKyThueDia(NhatKyThueDia instance);
    partial void UpdateNhatKyThueDia(NhatKyThueDia instance);
    partial void DeleteNhatKyThueDia(NhatKyThueDia instance);
    partial void InsertTuaDe(TuaDe instance);
    partial void UpdateTuaDe(TuaDe instance);
    partial void DeleteTuaDe(TuaDe instance);
    partial void InsertHangDoi(HangDoi instance);
    partial void UpdateHangDoi(HangDoi instance);
    partial void DeleteHangDoi(HangDoi instance);
    #endregion
		
		public QuanLyThueDiaDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.QuanLyChoThueBangDiaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThueDiaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThueDiaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThueDiaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThueDiaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dia> Dias
		{
			get
			{
				return this.GetTable<Dia>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiDia> LoaiDias
		{
			get
			{
				return this.GetTable<LoaiDia>();
			}
		}
		
		public System.Data.Linq.Table<Login> Logins
		{
			get
			{
				return this.GetTable<Login>();
			}
		}
		
		public System.Data.Linq.Table<NhatKyGhiNo> NhatKyGhiNos
		{
			get
			{
				return this.GetTable<NhatKyGhiNo>();
			}
		}
		
		public System.Data.Linq.Table<NhatKyThueDia> NhatKyThueDias
		{
			get
			{
				return this.GetTable<NhatKyThueDia>();
			}
		}
		
		public System.Data.Linq.Table<TuaDe> TuaDes
		{
			get
			{
				return this.GetTable<TuaDe>();
			}
		}
		
		public System.Data.Linq.Table<HangDoi> HangDois
		{
			get
			{
				return this.GetTable<HangDoi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dias")]
	public partial class Dia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDia;
		
		private string _TinhTrangThue;
		
		private string _TinhTrangDia;
		
		private string _IDTuaDe;
		
		private string _IDLoaiDia;
		
		private EntitySet<NhatKyGhiNo> _NhatKyGhiNos;
		
		private EntityRef<LoaiDia> _LoaiDia;
		
		private EntityRef<TuaDe> _TuaDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaChanging(int value);
    partial void OnMaDiaChanged();
    partial void OnTinhTrangThueChanging(string value);
    partial void OnTinhTrangThueChanged();
    partial void OnTinhTrangDiaChanging(string value);
    partial void OnTinhTrangDiaChanged();
    partial void OnIDTuaDeChanging(string value);
    partial void OnIDTuaDeChanged();
    partial void OnIDLoaiDiaChanging(string value);
    partial void OnIDLoaiDiaChanged();
    #endregion
		
		public Dia()
		{
			this._NhatKyGhiNos = new EntitySet<NhatKyGhiNo>(new Action<NhatKyGhiNo>(this.attach_NhatKyGhiNos), new Action<NhatKyGhiNo>(this.detach_NhatKyGhiNos));
			this._LoaiDia = default(EntityRef<LoaiDia>);
			this._TuaDe = default(EntityRef<TuaDe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDia
		{
			get
			{
				return this._MaDia;
			}
			set
			{
				if ((this._MaDia != value))
				{
					this.OnMaDiaChanging(value);
					this.SendPropertyChanging();
					this._MaDia = value;
					this.SendPropertyChanged("MaDia");
					this.OnMaDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangThue", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TinhTrangThue
		{
			get
			{
				return this._TinhTrangThue;
			}
			set
			{
				if ((this._TinhTrangThue != value))
				{
					this.OnTinhTrangThueChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangThue = value;
					this.SendPropertyChanged("TinhTrangThue");
					this.OnTinhTrangThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangDia", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TinhTrangDia
		{
			get
			{
				return this._TinhTrangDia;
			}
			set
			{
				if ((this._TinhTrangDia != value))
				{
					this.OnTinhTrangDiaChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangDia = value;
					this.SendPropertyChanged("TinhTrangDia");
					this.OnTinhTrangDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTuaDe", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string IDTuaDe
		{
			get
			{
				return this._IDTuaDe;
			}
			set
			{
				if ((this._IDTuaDe != value))
				{
					if (this._TuaDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTuaDeChanging(value);
					this.SendPropertyChanging();
					this._IDTuaDe = value;
					this.SendPropertyChanged("IDTuaDe");
					this.OnIDTuaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLoaiDia", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string IDLoaiDia
		{
			get
			{
				return this._IDLoaiDia;
			}
			set
			{
				if ((this._IDLoaiDia != value))
				{
					if (this._LoaiDia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDLoaiDiaChanging(value);
					this.SendPropertyChanging();
					this._IDLoaiDia = value;
					this.SendPropertyChanged("IDLoaiDia");
					this.OnIDLoaiDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dia_NhatKyGhiNo", Storage="_NhatKyGhiNos", ThisKey="MaDia", OtherKey="IDDia")]
		public EntitySet<NhatKyGhiNo> NhatKyGhiNos
		{
			get
			{
				return this._NhatKyGhiNos;
			}
			set
			{
				this._NhatKyGhiNos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDia_Dia", Storage="_LoaiDia", ThisKey="IDLoaiDia", OtherKey="MaLoai", IsForeignKey=true)]
		public LoaiDia LoaiDia
		{
			get
			{
				return this._LoaiDia.Entity;
			}
			set
			{
				LoaiDia previousValue = this._LoaiDia.Entity;
				if (((previousValue != value) 
							|| (this._LoaiDia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiDia.Entity = null;
						previousValue.Dias.Remove(this);
					}
					this._LoaiDia.Entity = value;
					if ((value != null))
					{
						value.Dias.Add(this);
						this._IDLoaiDia = value.MaLoai;
					}
					else
					{
						this._IDLoaiDia = default(string);
					}
					this.SendPropertyChanged("LoaiDia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuaDe_Dia", Storage="_TuaDe", ThisKey="IDTuaDe", OtherKey="MaTuaDe", IsForeignKey=true)]
		public TuaDe TuaDe
		{
			get
			{
				return this._TuaDe.Entity;
			}
			set
			{
				TuaDe previousValue = this._TuaDe.Entity;
				if (((previousValue != value) 
							|| (this._TuaDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuaDe.Entity = null;
						previousValue.Dias.Remove(this);
					}
					this._TuaDe.Entity = value;
					if ((value != null))
					{
						value.Dias.Add(this);
						this._IDTuaDe = value.MaTuaDe;
					}
					else
					{
						this._IDTuaDe = default(string);
					}
					this.SendPropertyChanged("TuaDe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhatKyGhiNos(NhatKyGhiNo entity)
		{
			this.SendPropertyChanging();
			entity.Dia = this;
		}
		
		private void detach_NhatKyGhiNos(NhatKyGhiNo entity)
		{
			this.SendPropertyChanging();
			entity.Dia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHangs")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _TenKhachHang;
		
		private string _SoDienThoai;
		
		private EntitySet<NhatKyGhiNo> _NhatKyGhiNos;
		
		private EntitySet<HangDoi> _HangDois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    #endregion
		
		public KhachHang()
		{
			this._NhatKyGhiNos = new EntitySet<NhatKyGhiNo>(new Action<NhatKyGhiNo>(this.attach_NhatKyGhiNos), new Action<NhatKyGhiNo>(this.detach_NhatKyGhiNos));
			this._HangDois = new EntitySet<HangDoi>(new Action<HangDoi>(this.attach_HangDois), new Action<HangDoi>(this.detach_HangDois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_NhatKyGhiNo", Storage="_NhatKyGhiNos", ThisKey="MaKhachHang", OtherKey="IDKhachHang")]
		public EntitySet<NhatKyGhiNo> NhatKyGhiNos
		{
			get
			{
				return this._NhatKyGhiNos;
			}
			set
			{
				this._NhatKyGhiNos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HangDoi", Storage="_HangDois", ThisKey="MaKhachHang", OtherKey="MaKhacHangs")]
		public EntitySet<HangDoi> HangDois
		{
			get
			{
				return this._HangDois;
			}
			set
			{
				this._HangDois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhatKyGhiNos(NhatKyGhiNo entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_NhatKyGhiNos(NhatKyGhiNo entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_HangDois(HangDoi entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HangDois(HangDoi entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiDias")]
	public partial class LoaiDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoai;
		
		private string _TenLoai;
		
		private int _ThoiGianChoPhepThue;
		
		private decimal _GiaThue;
		
		private EntitySet<Dia> _Dias;
		
		private EntitySet<TuaDe> _TuaDes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnThoiGianChoPhepThueChanging(int value);
    partial void OnThoiGianChoPhepThueChanged();
    partial void OnGiaThueChanging(decimal value);
    partial void OnGiaThueChanged();
    #endregion
		
		public LoaiDia()
		{
			this._Dias = new EntitySet<Dia>(new Action<Dia>(this.attach_Dias), new Action<Dia>(this.detach_Dias));
			this._TuaDes = new EntitySet<TuaDe>(new Action<TuaDe>(this.attach_TuaDes), new Action<TuaDe>(this.detach_TuaDes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianChoPhepThue", DbType="Int NOT NULL")]
		public int ThoiGianChoPhepThue
		{
			get
			{
				return this._ThoiGianChoPhepThue;
			}
			set
			{
				if ((this._ThoiGianChoPhepThue != value))
				{
					this.OnThoiGianChoPhepThueChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianChoPhepThue = value;
					this.SendPropertyChanged("ThoiGianChoPhepThue");
					this.OnThoiGianChoPhepThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThue", DbType="Money NOT NULL")]
		public decimal GiaThue
		{
			get
			{
				return this._GiaThue;
			}
			set
			{
				if ((this._GiaThue != value))
				{
					this.OnGiaThueChanging(value);
					this.SendPropertyChanging();
					this._GiaThue = value;
					this.SendPropertyChanged("GiaThue");
					this.OnGiaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDia_Dia", Storage="_Dias", ThisKey="MaLoai", OtherKey="IDLoaiDia")]
		public EntitySet<Dia> Dias
		{
			get
			{
				return this._Dias;
			}
			set
			{
				this._Dias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDia_TuaDe", Storage="_TuaDes", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<TuaDe> TuaDes
		{
			get
			{
				return this._TuaDes;
			}
			set
			{
				this._TuaDes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dias(Dia entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDia = this;
		}
		
		private void detach_Dias(Dia entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDia = null;
		}
		
		private void attach_TuaDes(TuaDe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDia = this;
		}
		
		private void detach_TuaDes(TuaDe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Logins")]
	public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserName;
		
		private string _Pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    #endregion
		
		public Login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhatKyGhiNo")]
	public partial class NhatKyGhiNo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _IDKhachHang;
		
		private System.Nullable<int> _IDDia;
		
		private decimal _SoTienNo;
		
		private EntityRef<Dia> _Dia;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIDKhachHangChanging(string value);
    partial void OnIDKhachHangChanged();
    partial void OnIDDiaChanging(System.Nullable<int> value);
    partial void OnIDDiaChanged();
    partial void OnSoTienNoChanging(decimal value);
    partial void OnSoTienNoChanged();
    #endregion
		
		public NhatKyGhiNo()
		{
			this._Dia = default(EntityRef<Dia>);
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKhachHang", DbType="VarChar(15)")]
		public string IDKhachHang
		{
			get
			{
				return this._IDKhachHang;
			}
			set
			{
				if ((this._IDKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDKhachHangChanging(value);
					this.SendPropertyChanging();
					this._IDKhachHang = value;
					this.SendPropertyChanged("IDKhachHang");
					this.OnIDKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDia", DbType="Int")]
		public System.Nullable<int> IDDia
		{
			get
			{
				return this._IDDia;
			}
			set
			{
				if ((this._IDDia != value))
				{
					if (this._Dia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDiaChanging(value);
					this.SendPropertyChanging();
					this._IDDia = value;
					this.SendPropertyChanged("IDDia");
					this.OnIDDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienNo", DbType="Money NOT NULL")]
		public decimal SoTienNo
		{
			get
			{
				return this._SoTienNo;
			}
			set
			{
				if ((this._SoTienNo != value))
				{
					this.OnSoTienNoChanging(value);
					this.SendPropertyChanging();
					this._SoTienNo = value;
					this.SendPropertyChanged("SoTienNo");
					this.OnSoTienNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dia_NhatKyGhiNo", Storage="_Dia", ThisKey="IDDia", OtherKey="MaDia", IsForeignKey=true)]
		public Dia Dia
		{
			get
			{
				return this._Dia.Entity;
			}
			set
			{
				Dia previousValue = this._Dia.Entity;
				if (((previousValue != value) 
							|| (this._Dia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dia.Entity = null;
						previousValue.NhatKyGhiNos.Remove(this);
					}
					this._Dia.Entity = value;
					if ((value != null))
					{
						value.NhatKyGhiNos.Add(this);
						this._IDDia = value.MaDia;
					}
					else
					{
						this._IDDia = default(Nullable<int>);
					}
					this.SendPropertyChanged("Dia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_NhatKyGhiNo", Storage="_KhachHang", ThisKey="IDKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.NhatKyGhiNos.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.NhatKyGhiNos.Add(this);
						this._IDKhachHang = value.MaKhachHang;
					}
					else
					{
						this._IDKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhatKyThueDia")]
	public partial class NhatKyThueDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _NgayChoThue;
		
		private string _MaTua;
		
		private string _MaDia;
		
		private string _MaKH;
		
		private int _SoLuongThue;
		
		private decimal _TienDatCoc;
		
		private System.Nullable<decimal> _PhiTreHen;
		
		private System.Nullable<System.DateTime> _NgayTraDia;
		
		private string _tinhtrangtradia;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNgayChoThueChanging(System.DateTime value);
    partial void OnNgayChoThueChanged();
    partial void OnMaTuaChanging(string value);
    partial void OnMaTuaChanged();
    partial void OnMaDiaChanging(string value);
    partial void OnMaDiaChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnSoLuongThueChanging(int value);
    partial void OnSoLuongThueChanged();
    partial void OnTienDatCocChanging(decimal value);
    partial void OnTienDatCocChanged();
    partial void OnPhiTreHenChanging(System.Nullable<decimal> value);
    partial void OnPhiTreHenChanged();
    partial void OnNgayTraDiaChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraDiaChanged();
    partial void OntinhtrangtradiaChanging(string value);
    partial void OntinhtrangtradiaChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public NhatKyThueDia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChoThue", DbType="DateTime NOT NULL")]
		public System.DateTime NgayChoThue
		{
			get
			{
				return this._NgayChoThue;
			}
			set
			{
				if ((this._NgayChoThue != value))
				{
					this.OnNgayChoThueChanging(value);
					this.SendPropertyChanging();
					this._NgayChoThue = value;
					this.SendPropertyChanged("NgayChoThue");
					this.OnNgayChoThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTua", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MaTua
		{
			get
			{
				return this._MaTua;
			}
			set
			{
				if ((this._MaTua != value))
				{
					this.OnMaTuaChanging(value);
					this.SendPropertyChanging();
					this._MaTua = value;
					this.SendPropertyChanged("MaTua");
					this.OnMaTuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDia", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MaDia
		{
			get
			{
				return this._MaDia;
			}
			set
			{
				if ((this._MaDia != value))
				{
					this.OnMaDiaChanging(value);
					this.SendPropertyChanging();
					this._MaDia = value;
					this.SendPropertyChanged("MaDia");
					this.OnMaDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongThue", DbType="Int NOT NULL")]
		public int SoLuongThue
		{
			get
			{
				return this._SoLuongThue;
			}
			set
			{
				if ((this._SoLuongThue != value))
				{
					this.OnSoLuongThueChanging(value);
					this.SendPropertyChanging();
					this._SoLuongThue = value;
					this.SendPropertyChanged("SoLuongThue");
					this.OnSoLuongThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienDatCoc", DbType="Money NOT NULL")]
		public decimal TienDatCoc
		{
			get
			{
				return this._TienDatCoc;
			}
			set
			{
				if ((this._TienDatCoc != value))
				{
					this.OnTienDatCocChanging(value);
					this.SendPropertyChanging();
					this._TienDatCoc = value;
					this.SendPropertyChanged("TienDatCoc");
					this.OnTienDatCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiTreHen", DbType="Money")]
		public System.Nullable<decimal> PhiTreHen
		{
			get
			{
				return this._PhiTreHen;
			}
			set
			{
				if ((this._PhiTreHen != value))
				{
					this.OnPhiTreHenChanging(value);
					this.SendPropertyChanging();
					this._PhiTreHen = value;
					this.SendPropertyChanged("PhiTreHen");
					this.OnPhiTreHenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTraDia", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTraDia
		{
			get
			{
				return this._NgayTraDia;
			}
			set
			{
				if ((this._NgayTraDia != value))
				{
					this.OnNgayTraDiaChanging(value);
					this.SendPropertyChanging();
					this._NgayTraDia = value;
					this.SendPropertyChanged("NgayTraDia");
					this.OnNgayTraDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrangtradia", DbType="NVarChar(30)")]
		public string tinhtrangtradia
		{
			get
			{
				return this._tinhtrangtradia;
			}
			set
			{
				if ((this._tinhtrangtradia != value))
				{
					this.OntinhtrangtradiaChanging(value);
					this.SendPropertyChanging();
					this._tinhtrangtradia = value;
					this.SendPropertyChanged("tinhtrangtradia");
					this.OntinhtrangtradiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuaDes")]
	public partial class TuaDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTuaDe;
		
		private string _NoiDungTuaDe;
		
		private string _ImageUrl;
		
		private System.Nullable<int> _SoLuongDia;
		
		private string _MaLoai;
		
		private EntitySet<Dia> _Dias;
		
		private EntitySet<HangDoi> _HangDois;
		
		private EntityRef<LoaiDia> _LoaiDia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTuaDeChanging(string value);
    partial void OnMaTuaDeChanged();
    partial void OnNoiDungTuaDeChanging(string value);
    partial void OnNoiDungTuaDeChanged();
    partial void OnImageUrlChanging(string value);
    partial void OnImageUrlChanged();
    partial void OnSoLuongDiaChanging(System.Nullable<int> value);
    partial void OnSoLuongDiaChanged();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    #endregion
		
		public TuaDe()
		{
			this._Dias = new EntitySet<Dia>(new Action<Dia>(this.attach_Dias), new Action<Dia>(this.detach_Dias));
			this._HangDois = new EntitySet<HangDoi>(new Action<HangDoi>(this.attach_HangDois), new Action<HangDoi>(this.detach_HangDois));
			this._LoaiDia = default(EntityRef<LoaiDia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTuaDe", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTuaDe
		{
			get
			{
				return this._MaTuaDe;
			}
			set
			{
				if ((this._MaTuaDe != value))
				{
					this.OnMaTuaDeChanging(value);
					this.SendPropertyChanging();
					this._MaTuaDe = value;
					this.SendPropertyChanged("MaTuaDe");
					this.OnMaTuaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTuaDe", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NoiDungTuaDe
		{
			get
			{
				return this._NoiDungTuaDe;
			}
			set
			{
				if ((this._NoiDungTuaDe != value))
				{
					this.OnNoiDungTuaDeChanging(value);
					this.SendPropertyChanging();
					this._NoiDungTuaDe = value;
					this.SendPropertyChanged("NoiDungTuaDe");
					this.OnNoiDungTuaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageUrl", DbType="NVarChar(MAX)")]
		public string ImageUrl
		{
			get
			{
				return this._ImageUrl;
			}
			set
			{
				if ((this._ImageUrl != value))
				{
					this.OnImageUrlChanging(value);
					this.SendPropertyChanging();
					this._ImageUrl = value;
					this.SendPropertyChanged("ImageUrl");
					this.OnImageUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDia", DbType="Int")]
		public System.Nullable<int> SoLuongDia
		{
			get
			{
				return this._SoLuongDia;
			}
			set
			{
				if ((this._SoLuongDia != value))
				{
					this.OnSoLuongDiaChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDia = value;
					this.SendPropertyChanged("SoLuongDia");
					this.OnSoLuongDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="VarChar(15)")]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._LoaiDia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuaDe_Dia", Storage="_Dias", ThisKey="MaTuaDe", OtherKey="IDTuaDe")]
		public EntitySet<Dia> Dias
		{
			get
			{
				return this._Dias;
			}
			set
			{
				this._Dias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuaDe_HangDoi", Storage="_HangDois", ThisKey="MaTuaDe", OtherKey="MaTuaDe")]
		public EntitySet<HangDoi> HangDois
		{
			get
			{
				return this._HangDois;
			}
			set
			{
				this._HangDois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDia_TuaDe", Storage="_LoaiDia", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true)]
		public LoaiDia LoaiDia
		{
			get
			{
				return this._LoaiDia.Entity;
			}
			set
			{
				LoaiDia previousValue = this._LoaiDia.Entity;
				if (((previousValue != value) 
							|| (this._LoaiDia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiDia.Entity = null;
						previousValue.TuaDes.Remove(this);
					}
					this._LoaiDia.Entity = value;
					if ((value != null))
					{
						value.TuaDes.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(string);
					}
					this.SendPropertyChanged("LoaiDia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dias(Dia entity)
		{
			this.SendPropertyChanging();
			entity.TuaDe = this;
		}
		
		private void detach_Dias(Dia entity)
		{
			this.SendPropertyChanging();
			entity.TuaDe = null;
		}
		
		private void attach_HangDois(HangDoi entity)
		{
			this.SendPropertyChanging();
			entity.TuaDe = this;
		}
		
		private void detach_HangDois(HangDoi entity)
		{
			this.SendPropertyChanging();
			entity.TuaDe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangDois")]
	public partial class HangDoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MaKhacHangs;
		
		private string _MaTuaDe;
		
		private int _ThuTu;
		
		private System.Nullable<int> _SoLuongDat;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<TuaDe> _TuaDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaKhacHangsChanging(string value);
    partial void OnMaKhacHangsChanged();
    partial void OnMaTuaDeChanging(string value);
    partial void OnMaTuaDeChanged();
    partial void OnThuTuChanging(int value);
    partial void OnThuTuChanged();
    partial void OnSoLuongDatChanging(System.Nullable<int> value);
    partial void OnSoLuongDatChanged();
    #endregion
		
		public HangDoi()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._TuaDe = default(EntityRef<TuaDe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhacHangs", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MaKhacHangs
		{
			get
			{
				return this._MaKhacHangs;
			}
			set
			{
				if ((this._MaKhacHangs != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhacHangsChanging(value);
					this.SendPropertyChanging();
					this._MaKhacHangs = value;
					this.SendPropertyChanged("MaKhacHangs");
					this.OnMaKhacHangsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTuaDe", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MaTuaDe
		{
			get
			{
				return this._MaTuaDe;
			}
			set
			{
				if ((this._MaTuaDe != value))
				{
					if (this._TuaDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTuaDeChanging(value);
					this.SendPropertyChanging();
					this._MaTuaDe = value;
					this.SendPropertyChanged("MaTuaDe");
					this.OnMaTuaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuTu", DbType="Int NOT NULL")]
		public int ThuTu
		{
			get
			{
				return this._ThuTu;
			}
			set
			{
				if ((this._ThuTu != value))
				{
					this.OnThuTuChanging(value);
					this.SendPropertyChanging();
					this._ThuTu = value;
					this.SendPropertyChanged("ThuTu");
					this.OnThuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDat", DbType="Int")]
		public System.Nullable<int> SoLuongDat
		{
			get
			{
				return this._SoLuongDat;
			}
			set
			{
				if ((this._SoLuongDat != value))
				{
					this.OnSoLuongDatChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDat = value;
					this.SendPropertyChanged("SoLuongDat");
					this.OnSoLuongDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HangDoi", Storage="_KhachHang", ThisKey="MaKhacHangs", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HangDois.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HangDois.Add(this);
						this._MaKhacHangs = value.MaKhachHang;
					}
					else
					{
						this._MaKhacHangs = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuaDe_HangDoi", Storage="_TuaDe", ThisKey="MaTuaDe", OtherKey="MaTuaDe", IsForeignKey=true)]
		public TuaDe TuaDe
		{
			get
			{
				return this._TuaDe.Entity;
			}
			set
			{
				TuaDe previousValue = this._TuaDe.Entity;
				if (((previousValue != value) 
							|| (this._TuaDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuaDe.Entity = null;
						previousValue.HangDois.Remove(this);
					}
					this._TuaDe.Entity = value;
					if ((value != null))
					{
						value.HangDois.Add(this);
						this._MaTuaDe = value.MaTuaDe;
					}
					else
					{
						this._MaTuaDe = default(string);
					}
					this.SendPropertyChanged("TuaDe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
